/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package webscrapping;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.select.Elements;
/**
 *
 * @author jesus
 */

public class Ui extends javax.swing.JFrame {
    public Webscrapping ws = new Webscrapping();
    Document doc;

    /**
     * Creates new form Ui
     */
    public Ui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        site = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tabPagina = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        resposta = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtPagina = new javax.swing.JTextArea();
        qtdLinks = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("mejCrawler");

        jButton1.setText("Crawlear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        resposta.setEditable(false);
        resposta.setColumns(20);
        resposta.setRows(5);
        jScrollPane1.setViewportView(resposta);

        tabPagina.addTab("titulo", jScrollPane1);

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane2.setViewportView(txtDescription);

        tabPagina.addTab("Description", jScrollPane2);

        txtPagina.setColumns(20);
        txtPagina.setRows(5);
        jScrollPane3.setViewportView(txtPagina);

        tabPagina.addTab("paginas", jScrollPane3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tabPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(site)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(qtdLinks)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(site, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtdLinks)
                .addGap(18, 18, 18)
                .addComponent(tabPagina, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
            // TODO add your handling code here:
            //doc = Jsoup.connect(site.getText()).get();
            //setResposta(doc.title());
            
            verificaLinks(site.getText());
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ui().setVisible(true);
            }
        });
    }
    public String getNomeSite(){
        return site.getText();
    }
    public void verificaLinks(String url){
        int totalLinks = 0;
        int linkAtual = 0;
        qtdLinks.setText("Quantidade de links: "+totalLinks);
        Document doc;
        try {
            doc = Jsoup.connect(url).get();
            Elements links = doc.select("a");
            String relHref = links.attr("href"); // == "/"
            String absHref = links.attr("abs:href"); // "http://jsoup.org/"
            for(Element link : links){
                totalLinks = links.size();
                if(!link.attr("rel").equals("nofollow")){
                    if(!link.attr("href").contains("#")){
                        linkAtual++;
                        
                        qtdLinks.setText("Quantidade de links: "+linkAtual+"/"+totalLinks);
                        String linkInteiro = link.attr("href");
                        System.out.println(linkInteiro);
                        //setTxtPagina(linkInteiro);
                        pegaTitle(linkInteiro);
                        geraDados(linkInteiro);
                }
                    
            }
                
        }
            
        } catch (IOException ex) {
            Logger.getLogger(Ui.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public void pegaTitle(String url){
        try {
            doc = Jsoup.connect(url).get();
            setResposta(doc.title());
        } catch (IOException ex) {
            Logger.getLogger(Ui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void geraDados(String url){
       
        Document document;
        try {
            document = Jsoup.connect(url).get();
            String description = document.select("meta[name=description]").get(0).attr("content");
            //if((description.length() > 160)|| (description.length() < 140) ){
                setTxtDescription("quantidade de caracteres "+description.length());
            //}
            
        } catch (IOException ex) {
            Logger.getLogger(Ui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         
      
    }
public void setResposta(String isso) {
        resposta.insert(isso, resposta.getCaretPosition());
        resposta.append("\n");
    }
public void setTxtDescription(String desc){
    txtDescription.insert(desc, txtDescription.getCaretPosition());
    txtDescription.append("\n");
}
public void setTxtPagina(String desc){
    txtPagina.insert(desc, txtPagina.getCaretPosition());
    txtPagina.append("\n");
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel qtdLinks;
    private javax.swing.JTextArea resposta;
    private javax.swing.JTextField site;
    private javax.swing.JTabbedPane tabPagina;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextArea txtPagina;
    // End of variables declaration//GEN-END:variables
}
